apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp
  label: 
    app:web
spec: 
  replicas: {{default 1 .Values.replicas | int}}
  selector: 
    matchlabels: 
     app:web
  template: 
    metadata:
      name: myapp
      labels:
        app:web
    spec:
      containers:
       - name: myapp
         image: {{.Values.image.name}} : {{.Values.image.tag}}
         imagePullPolicy: {{.Values.image.pullpolicy}}
         ports: 
         - containerPort: {{.Values.ports.containerPort}}